# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './PyQt5Designer/main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.main_tab.setObjectName("main_tab")
        self.main_tab_start = QtWidgets.QWidget()
        self.main_tab_start.setObjectName("main_tab_start")
        self.main_tab.addTab(self.main_tab_start, "")
        self.main_tab_build = QtWidgets.QWidget()
        self.main_tab_build.setObjectName("main_tab_build")
        self.build_tab = QtWidgets.QTabWidget(self.main_tab_build)
        self.build_tab.setGeometry(QtCore.QRect(0, 0, 1200, 730))
        self.build_tab.setObjectName("build_tab")
        self.build_tab_race = QtWidgets.QWidget()
        self.build_tab_race.setObjectName("build_tab_race")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.build_tab_race)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 741, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.race_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.race_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.race_verticalLayout.setObjectName("race_verticalLayout")
        self.race_label_listWidget = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.race_label_listWidget.sizePolicy().hasHeightForWidth())
        self.race_label_listWidget.setSizePolicy(sizePolicy)
        self.race_label_listWidget.setObjectName("race_label_listWidget")
        self.race_verticalLayout.addWidget(self.race_label_listWidget)
        self.race_listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.race_listWidget.sizePolicy().hasHeightForWidth())
        self.race_listWidget.setSizePolicy(sizePolicy)
        self.race_listWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.race_listWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.race_listWidget.setObjectName("race_listWidget")
        self.race_verticalLayout.addWidget(self.race_listWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.race_verticalLayout.addItem(spacerItem)
        self.subrace_label_listWidget = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.subrace_label_listWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.subrace_label_listWidget.sizePolicy().hasHeightForWidth())
        self.subrace_label_listWidget.setSizePolicy(sizePolicy)
        self.subrace_label_listWidget.setObjectName("subrace_label_listWidget")
        self.race_verticalLayout.addWidget(self.subrace_label_listWidget)
        self.subrace_listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.subrace_listWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.subrace_listWidget.sizePolicy().hasHeightForWidth())
        self.subrace_listWidget.setSizePolicy(sizePolicy)
        self.subrace_listWidget.setMinimumSize(QtCore.QSize(0, 41))
        self.subrace_listWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.subrace_listWidget.setBaseSize(QtCore.QSize(0, 0))
        self.subrace_listWidget.setObjectName("subrace_listWidget")
        self.race_verticalLayout.addWidget(self.subrace_listWidget)
        self.race_desc_view = QtWebEngineWidgets.QWebEngineView(self.build_tab_race)
        self.race_desc_view.setGeometry(QtCore.QRect(770, 10, 421, 671))
        self.race_desc_view.setUrl(QtCore.QUrl("about:blank"))
        self.race_desc_view.setObjectName("race_desc_view")
        self.build_tab.addTab(self.build_tab_race, "")
        self.build_tab_class = QtWidgets.QWidget()
        self.build_tab_class.setObjectName("build_tab_class")
        self.build_tab.addTab(self.build_tab_class, "")
        self.build_tab_background = QtWidgets.QWidget()
        self.build_tab_background.setObjectName("build_tab_background")
        self.build_tab.addTab(self.build_tab_background, "")
        self.build_tab_scores = QtWidgets.QWidget()
        self.build_tab_scores.setObjectName("build_tab_scores")
        self.build_tab.addTab(self.build_tab_scores, "")
        self.build_tab_lang = QtWidgets.QWidget()
        self.build_tab_lang.setObjectName("build_tab_lang")
        self.build_tab.addTab(self.build_tab_lang, "")
        self.build_tab_prof = QtWidgets.QWidget()
        self.build_tab_prof.setObjectName("build_tab_prof")
        self.build_tab.addTab(self.build_tab_prof, "")
        self.build_tab_feats = QtWidgets.QWidget()
        self.build_tab_feats.setObjectName("build_tab_feats")
        self.build_tab.addTab(self.build_tab_feats, "")
        self.main_tab.addTab(self.main_tab_build, "")
        self.main_tab_magic = QtWidgets.QWidget()
        self.main_tab_magic.setObjectName("main_tab_magic")
        self.main_tab.addTab(self.main_tab_magic, "")
        self.main_tab_equipment = QtWidgets.QWidget()
        self.main_tab_equipment.setObjectName("main_tab_equipment")
        self.main_tab.addTab(self.main_tab_equipment, "")
        self.main_tab_manage = QtWidgets.QWidget()
        self.main_tab_manage.setObjectName("main_tab_manage")
        self.main_tab.addTab(self.main_tab_manage, "")
        self.main_tab_charSheet = QtWidgets.QWidget()
        self.main_tab_charSheet.setObjectName("main_tab_charSheet")
        self.main_tab.addTab(self.main_tab_charSheet, "")
        self.newchar_frame = QtWidgets.QFrame(self.centralwidget)
        self.newchar_frame.setEnabled(True)
        self.newchar_frame.setGeometry(QtCore.QRect(800, 0, 400, 750))
        self.newchar_frame.setAutoFillBackground(True)
        self.newchar_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.newchar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newchar_frame.setObjectName("newchar_frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.newchar_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 442, 751))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.newchar_level_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_level_label.sizePolicy().hasHeightForWidth())
        self.newchar_level_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.newchar_level_label.setFont(font)
        self.newchar_level_label.setObjectName("newchar_level_label")
        self.horizontalLayout_3.addWidget(self.newchar_level_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.newchar_gender_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.newchar_gender_label.setFont(font)
        self.newchar_gender_label.setObjectName("newchar_gender_label")
        self.horizontalLayout_3.addWidget(self.newchar_gender_label)
        self.gridLayout.addLayout(self.horizontalLayout_3, 12, 1, 1, 1)
        self.newchar_imgplace = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_imgplace.sizePolicy().hasHeightForWidth())
        self.newchar_imgplace.setSizePolicy(sizePolicy)
        self.newchar_imgplace.setMinimumSize(QtCore.QSize(70, 70))
        self.newchar_imgplace.setAlignment(QtCore.Qt.AlignCenter)
        self.newchar_imgplace.setObjectName("newchar_imgplace")
        self.gridLayout.addWidget(self.newchar_imgplace, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        self.newchar_details = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_details.sizePolicy().hasHeightForWidth())
        self.newchar_details.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.newchar_details.setFont(font)
        self.newchar_details.setObjectName("newchar_details")
        self.gridLayout.addWidget(self.newchar_details, 6, 1, 1, 1)
        self.newchar_generation_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_generation_label.sizePolicy().hasHeightForWidth())
        self.newchar_generation_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.newchar_generation_label.setFont(font)
        self.newchar_generation_label.setObjectName("newchar_generation_label")
        self.gridLayout.addWidget(self.newchar_generation_label, 15, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 11, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 5, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 14, 1, 1, 1)
        self.newchar_name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_name_label.sizePolicy().hasHeightForWidth())
        self.newchar_name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.newchar_name_label.setFont(font)
        self.newchar_name_label.setObjectName("newchar_name_label")
        self.gridLayout.addWidget(self.newchar_name_label, 9, 1, 1, 1)
        self.newchar_details_sub = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_details_sub.sizePolicy().hasHeightForWidth())
        self.newchar_details_sub.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.newchar_details_sub.setFont(font)
        self.newchar_details_sub.setObjectName("newchar_details_sub")
        self.gridLayout.addWidget(self.newchar_details_sub, 7, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newchar_level_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.newchar_level_combobox.setObjectName("newchar_level_combobox")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.newchar_level_combobox.addItem("")
        self.horizontalLayout_2.addWidget(self.newchar_level_combobox)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.newchar_gender_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_gender_combobox.sizePolicy().hasHeightForWidth())
        self.newchar_gender_combobox.setSizePolicy(sizePolicy)
        self.newchar_gender_combobox.setObjectName("newchar_gender_combobox")
        self.newchar_gender_combobox.addItem("")
        self.newchar_gender_combobox.addItem("")
        self.newchar_gender_combobox.addItem("")
        self.newchar_gender_combobox.addItem("")
        self.horizontalLayout_2.addWidget(self.newchar_gender_combobox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 13, 1, 1, 1)
        self.newchar_title = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_title.sizePolicy().hasHeightForWidth())
        self.newchar_title.setSizePolicy(sizePolicy)
        self.newchar_title.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.newchar_title.setFont(font)
        self.newchar_title.setFrameShape(QtWidgets.QFrame.Box)
        self.newchar_title.setMidLineWidth(0)
        self.newchar_title.setScaledContents(True)
        self.newchar_title.setAlignment(QtCore.Qt.AlignCenter)
        self.newchar_title.setIndent(-1)
        self.newchar_title.setObjectName("newchar_title")
        self.gridLayout.addWidget(self.newchar_title, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 2, 1, 1)
        self.newchar_name = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_name.sizePolicy().hasHeightForWidth())
        self.newchar_name.setSizePolicy(sizePolicy)
        self.newchar_name.setMinimumSize(QtCore.QSize(0, 0))
        self.newchar_name.setMaximumSize(QtCore.QSize(16777215, 25))
        self.newchar_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.newchar_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.newchar_name.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.newchar_name.setMaximumBlockCount(16)
        self.newchar_name.setObjectName("newchar_name")
        self.gridLayout.addWidget(self.newchar_name, 10, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 387, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem9, 17, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.newchar_cancel_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.newchar_cancel_button.setObjectName("newchar_cancel_button")
        self.horizontalLayout.addWidget(self.newchar_cancel_button)
        self.gridLayout.addLayout(self.horizontalLayout, 19, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem11, 20, 1, 1, 1)
        self.newchar_generation_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.newchar_generation_combobox.setObjectName("newchar_generation_combobox")
        self.newchar_generation_combobox.addItem("")
        self.gridLayout.addWidget(self.newchar_generation_combobox, 16, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem13, 8, 1, 1, 1)
        self.newchar_button = QtWidgets.QPushButton(self.centralwidget)
        self.newchar_button.setGeometry(QtCore.QRect(1140, 0, 60, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newchar_button.sizePolicy().hasHeightForWidth())
        self.newchar_button.setSizePolicy(sizePolicy)
        self.newchar_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.newchar_button.setFont(font)
        self.newchar_button.setText("")
        icon = QtGui.QIcon.fromTheme("add")
        self.newchar_button.setIcon(icon)
        self.newchar_button.setIconSize(QtCore.QSize(64, 64))
        self.newchar_button.setObjectName("newchar_button")
        self.main_tab.raise_()
        self.newchar_button.raise_()
        self.newchar_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Character = QtWidgets.QAction(MainWindow)
        self.actionNew_Character.setObjectName("actionNew_Character")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_Character_Sheet_PDF = QtWidgets.QAction(MainWindow)
        self.actionSave_Character_Sheet_PDF.setEnabled(False)
        self.actionSave_Character_Sheet_PDF.setObjectName("actionSave_Character_Sheet_PDF")
        self.actionExit_Application = QtWidgets.QAction(MainWindow)
        self.actionExit_Application.setObjectName("actionExit_Application")
        self.actionPortraits_Gallery = QtWidgets.QAction(MainWindow)
        self.actionPortraits_Gallery.setEnabled(False)
        self.actionPortraits_Gallery.setObjectName("actionPortraits_Gallery")
        self.actionCharacter_Sheet_View = QtWidgets.QAction(MainWindow)
        self.actionCharacter_Sheet_View.setEnabled(False)
        self.actionCharacter_Sheet_View.setObjectName("actionCharacter_Sheet_View")
        self.actionCompendium = QtWidgets.QAction(MainWindow)
        self.actionCompendium.setObjectName("actionCompendium")
        self.actionNext_Selection = QtWidgets.QAction(MainWindow)
        self.actionNext_Selection.setEnabled(False)
        self.actionNext_Selection.setObjectName("actionNext_Selection")
        self.actionEnable_Selection_Flow = QtWidgets.QAction(MainWindow)
        self.actionEnable_Selection_Flow.setCheckable(True)
        self.actionEnable_Selection_Flow.setEnabled(False)
        self.actionEnable_Selection_Flow.setObjectName("actionEnable_Selection_Flow")
        self.actionApplication_Settings = QtWidgets.QAction(MainWindow)
        self.actionApplication_Settings.setEnabled(True)
        self.actionApplication_Settings.setObjectName("actionApplication_Settings")
        self.actionGet_Started = QtWidgets.QAction(MainWindow)
        self.actionGet_Started.setObjectName("actionGet_Started")
        self.actionNews = QtWidgets.QAction(MainWindow)
        self.actionNews.setObjectName("actionNews")
        self.actionAdditonal_Content = QtWidgets.QAction(MainWindow)
        self.actionAdditonal_Content.setObjectName("actionAdditonal_Content")
        self.actionReleases = QtWidgets.QAction(MainWindow)
        self.actionReleases.setObjectName("actionReleases")
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        self.build_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aurora-Clone"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.main_tab_start), _translate("MainWindow", "START"))
        self.race_label_listWidget.setText(_translate("MainWindow", "Races"))
        self.race_listWidget.setSortingEnabled(True)
        self.subrace_label_listWidget.setText(_translate("MainWindow", "SubRaces"))
        self.build_tab.setTabText(self.build_tab.indexOf(self.build_tab_race), _translate("MainWindow", "RACE"))
        self.build_tab.setTabText(self.build_tab.indexOf(self.build_tab_class), _translate("MainWindow", "CLASS"))
        self.build_tab.setTabText(self.build_tab.indexOf(self.build_tab_background), _translate("MainWindow", "BACKGROUND"))
        self.build_tab.setTabText(self.build_tab.indexOf(self.build_tab_scores), _translate("MainWindow", "ABILITY SCORES"))
        self.build_tab.setTabText(self.build_tab.indexOf(self.build_tab_lang), _translate("MainWindow", "LANGUAGES"))
        self.build_tab.setTabText(self.build_tab.indexOf(self.build_tab_prof), _translate("MainWindow", "PROFICIENCIES"))
        self.build_tab.setTabText(self.build_tab.indexOf(self.build_tab_feats), _translate("MainWindow", "FEATS"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.main_tab_build), _translate("MainWindow", "BUILD"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.main_tab_magic), _translate("MainWindow", "MAGIC"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.main_tab_equipment), _translate("MainWindow", "EQUIPMENT"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.main_tab_manage), _translate("MainWindow", "MANAGE"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.main_tab_charSheet), _translate("MainWindow", "CHARACTER SHEET"))
        self.newchar_level_label.setText(_translate("MainWindow", "STARTING LEVEL"))
        self.newchar_gender_label.setText(_translate("MainWindow", "GENDER"))
        self.newchar_imgplace.setText(_translate("MainWindow", "IMG_PLACEHOLDER"))
        self.newchar_details.setText(_translate("MainWindow", "CHARACTER DETAILS"))
        self.newchar_generation_label.setText(_translate("MainWindow", "ABILITIES GENERATION OPTION"))
        self.newchar_name_label.setText(_translate("MainWindow", "NAME"))
        self.newchar_details_sub.setText(_translate("MainWindow", "Start with some basic details for your character."))
        self.newchar_level_combobox.setItemText(0, _translate("MainWindow", "1"))
        self.newchar_level_combobox.setItemText(1, _translate("MainWindow", "2"))
        self.newchar_level_combobox.setItemText(2, _translate("MainWindow", "3"))
        self.newchar_level_combobox.setItemText(3, _translate("MainWindow", "4"))
        self.newchar_level_combobox.setItemText(4, _translate("MainWindow", "5"))
        self.newchar_level_combobox.setItemText(5, _translate("MainWindow", "6"))
        self.newchar_level_combobox.setItemText(6, _translate("MainWindow", "7"))
        self.newchar_level_combobox.setItemText(7, _translate("MainWindow", "8"))
        self.newchar_level_combobox.setItemText(8, _translate("MainWindow", "9"))
        self.newchar_level_combobox.setItemText(9, _translate("MainWindow", "10"))
        self.newchar_level_combobox.setItemText(10, _translate("MainWindow", "11"))
        self.newchar_level_combobox.setItemText(11, _translate("MainWindow", "12"))
        self.newchar_level_combobox.setItemText(12, _translate("MainWindow", "13"))
        self.newchar_level_combobox.setItemText(13, _translate("MainWindow", "14"))
        self.newchar_level_combobox.setItemText(14, _translate("MainWindow", "15"))
        self.newchar_level_combobox.setItemText(15, _translate("MainWindow", "16"))
        self.newchar_level_combobox.setItemText(16, _translate("MainWindow", "17"))
        self.newchar_level_combobox.setItemText(17, _translate("MainWindow", "18"))
        self.newchar_level_combobox.setItemText(18, _translate("MainWindow", "19"))
        self.newchar_level_combobox.setItemText(19, _translate("MainWindow", "20"))
        self.newchar_gender_combobox.setItemText(0, _translate("MainWindow", "Masculine"))
        self.newchar_gender_combobox.setItemText(1, _translate("MainWindow", "Feminine"))
        self.newchar_gender_combobox.setItemText(2, _translate("MainWindow", "Androgynous"))
        self.newchar_gender_combobox.setItemText(3, _translate("MainWindow", "Construct"))
        self.newchar_title.setText(_translate("MainWindow", "   NEW CHARACTER"))
        self.pushButton_2.setText(_translate("MainWindow", "CREATE CHARACTER"))
        self.newchar_cancel_button.setText(_translate("MainWindow", "CANCEL"))
        self.newchar_generation_combobox.setItemText(0, _translate("MainWindow", "Point Buy"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_Character.setText(_translate("MainWindow", "New Character"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_Character_Sheet_PDF.setText(_translate("MainWindow", "Save Character Sheet (PDF)"))
        self.actionExit_Application.setText(_translate("MainWindow", "Exit Application"))
        self.actionPortraits_Gallery.setText(_translate("MainWindow", "Portraits Gallery"))
        self.actionCharacter_Sheet_View.setText(_translate("MainWindow", "Character Sheet View"))
        self.actionCompendium.setText(_translate("MainWindow", "Compendium"))
        self.actionNext_Selection.setText(_translate("MainWindow", "Next Selection"))
        self.actionEnable_Selection_Flow.setText(_translate("MainWindow", "Enable Selection Flow"))
        self.actionApplication_Settings.setText(_translate("MainWindow", "Application Settings"))
        self.actionGet_Started.setText(_translate("MainWindow", "Get Started"))
        self.actionNews.setText(_translate("MainWindow", "News"))
        self.actionAdditonal_Content.setText(_translate("MainWindow", "Additonal Content"))
        self.actionReleases.setText(_translate("MainWindow", "Releases"))

from PyQt5 import QtWebEngineWidgets
